trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- task: SSH@0
  inputs:
    sshEndpoint: 'Terravity sc147'
    runOptions: 'script'
    scriptPath: '/web/m-snooker/deploy.sh'
    readyTimeout: '20000'